name: Build-&-Deploy

on:
  push:
    branches:
      - main
    paths:
      # run only if a file under /backend/ was modified/added/removed
      - "backend/**"
      # still run if you edit this workflow itself
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLUSTER_ENDPOINT: ${{ secrets.CLUSTER_ENDPOINT }}
      DB_SECRET_NAME: ${{ secrets.DB_SECRET_NAME }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install CDK and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/infrastructure/requirements.txt
          npm install -g aws-cdk

      - name: CDK Synth
        working-directory: cdk
        run: cdk synth

      - name: CDK Deploy
        working-directory: cdk
        run: cdk deploy --require-approval never
